### ISSUE TITLE
How to download a part of the video

### ISSUE THREAD

**Issue by ChinaIceF** [Resheba/vk-video-download#2]
What should I do if I want to download a specific segment of a video or start downloading from a certain point in time in the video?

**Comment by Resheba** [comment]
Gruß!
If you need to get a video from a specific date, you can do it by adding QUERY params `start={any second}' to the player video

The upgraded code will look like this: 
`57 | download_url = get_video_url(player_url) + f'&start={60}`

**Comment by Resheba** [comment]
See last repository updates.
(Commit [7bea691](https://github.com/Resheba/vk-video-download/commit/7bea691d3ec5934ef01268dfd0473b95f3a6931a))

**Comment by ChinaIceF** [comment]
Thanks a lot.
